---
title: Icetea Platform
timezone: UTC
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "https://icetea.io/images/share/home.png"
    category: blog
    author: thi
- scope:
    path: ''
    type: pages
  values:
    image: "https://icetea.io/images/share/home.png"
lang: vi
description: Practical Blockchain for Real World Use Cases.
baseurl: "/"
url: https://blog.icetea.io
markdown: kramdown
theme: minima
show_excerpts: true
author: Icetea Platform
logo: "https://icetea.io/images/share/home.png"
facebook:
  app_id: 2178421482485741
  publisher: https://facebook.com/tradatech
plugins:
- jekyll-feed
prose:
  siteurl: 'http://blog.icetea.io/'
  media: '_uploads'
